---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: myteam
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/dge4711/workshop-flux-myteam.git
